# Colors
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)

# Screen Dimensions
SCREEN_WIDTH = 960
SCREEN_HEIGHT = 720
SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)

# Player attributes
PLAYER_SPEED = 7
PLAYER_GRAVITY = 0.5
PLAYER_FRICTION = 0.8
PLAYER_JUMP_HEIGHT = 10.5

# Guard attributes
GUARD_SPEED = 1.5
